#$#
# ** Abbuchung-Realname ungleich Realname
#     <Ustrd>MEMBER (REGULAER) 0551 SVEN BROENSTRUP SVEN BROENSTRUR</Ustrd>
#     <Ustrd>MEMBER (REGULAER) 00029 ANDRE HERMSBUSCH ANDRE MACKENBACH</Ustrd>
#     <Ustrd>MEMBER (REGULAER) 00046 JUDITH ROSENSTOCK JUDITH JAHNKE</Ustrd>
#     <Ustrd>MEMBER (REGULAER) 00233 UWE KAMPER UWE KEMPER</Ustrd>
#     <Ustrd>MEMBER (REGULAER) 00253 VOLKMAR MAI VOLKMAR MAY</Ustrd>
